version: '3.7'
services:
  postgres:
    image: postgres:10
    ports:
      - "5433:5432"
    networks:
      - druzhba
    stop_grace_period: 30s
    environment:
      POSTGRES_DB: druzhba_test
      POSTGRES_PASSWORD: 'postgres_root_password'

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - "3307:3306"
    networks:
      - druzhba
    volumes:
      - ./test/init_mysql:/docker-entrypoint-initdb.d
    stop_grace_period: 30s"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql_root_password'

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python setup.py test"
    env_file:
      - ./.env.test.docker
    volumes:
      - .:/app
    networks:
      - druzhba

  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:8000"
    command: bash -c "pip install -e .[dev] && cd ./docs && make html && cd ./_build/html && python -m http.server 8000"

networks:
  druzhba:
